### ISSUE TITLE
@babel/polyfill has been deprecated

### ISSUE THREAD

**Issue by erhunt29** [TinkoffCreditSystems/tramvai#2]
Why are you still using @babel/polyfill  in 2021 ?
https://github.com/TinkoffCreditSystems/tramvai/blob/main/packages/cli/package.json#L47

It's deprecated package by Babel team
https://www.npmjs.com/package/@babel/polyfill

**Comment by SuperOleg39** [comment]
Hi!

Thanks for the report!

We don't use @babel/polyfill, but forget to remove it from cli dependencies.

We don't include polyfills automatically, but support [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry) with `useBuiltIns: 'entry'` and `browserslist` respect

Source code for babel-preset-env configuration you can find [here](https://github.com/TinkoffCreditSystems/tramvai/blob/main/packages/cli/src/library/babel/index.ts#L102)

If you want to add polyfills for tramvai application, here is few steps:

1. Create `src/polyfill.ts` file

    ```js
    import 'core-js/stable';
    ```

1. Add link to polyfill in `tramvai.json` file

    ```json
    {
      "projects": {
        "myAppName": {
          ...
          "commands": {
            "build": {
              "options": {
                ...
                "polyfill": "src/polyfill.ts"
              }
            }
          }
        }
      }
    }
    ```

1. [optional] add custom `POLYFILL_CONDITION` provider, default value you can find [here](https://github.com/TinkoffCreditSystems/tramvai/blob/9db5aa3c1f87e5db2c0e2c52ea9de7e241efe8b8/packages/modules/render/src/server.ts#L31)

Our documentation `how to enable polyfills` live in private `@tinkoff/pack-polyfills` package, so i think we will publish this package to open source at next releases.

**Comment by SuperOleg39** [comment]
Just publish `@tinkoff/pack-polyfills` library, documentation available [here](https://tramvai.dev/docs/how-to/how-to-enable-polyfills)

Also, remove `@babel/polyfill` :)

Thank you!
