### ISSUE TITLE
Please add CHANGELOG.md about changes :)

### ISSUE THREAD

**Issue by splincode** [TinkoffCreditSystems/tramvai#3]

**Comment by SuperOleg39** [comment]
Hi!

Unfortunately, we don't have a public changelogs at now.

According to [CONTRIBUTING.md](https://github.com/TinkoffCreditSystems/tramvai/blob/main/CONTRIBUTING.md), all work on `tramvai` is done in a private repository, where we made untranslated commits, which can contain sensitive information.

So, we use [Copybara](https://github.com/google/copybara) to mirror all releases to Github, and Copybara squash all private commits to one public release commit.

I only can update some release tags manually, if there are a important changes, for example [1.8.3 release](https://github.com/TinkoffCreditSystems/tramvai/releases/tag/v1.8.3)

At the future, we will improve public releases processes and will try to automatically generate changelog.
