### ISSUE TITLE
sync .eslintrc and .tsconfig.json between project types

### ISSUE THREAD

**Issue by vedmalex** [TinkoffCreditSystems/tramvai#4]
using @tramvai/cli with option  Support for multiple applications in one repository  
When using that option vscode linter show errors in files, but still compiles it
![2021-12-20_18-06-12](https://user-images.githubusercontent.com/899848/146788491-5130439c-5f20-4b25-9139-1310cfc86666.png)

wheather this is not the case for single app per repository
![2021-12-20_18-07-24](https://user-images.githubusercontent.com/899848/146788781-c448ebd4-56f4-4092-befd-9d542f2941ca.png)

**Comment by meskill** [comment]
Thanks for the report, it will be fixed soon

**Comment by meskill** [comment]
It was fixed in [v1.46.10](https://github.com/TinkoffCreditSystems/tramvai/commit/28fd695b4155363ccbffb29029cc62eac308bb79)
