### ISSUE TITLE
Does it support build for edge runtime?

### ISSUE THREAD

**Issue by polRk** [TinkoffCreditSystems/tramvai#7]

**Comment by SuperOleg39** [comment]
Hello!

No, at this moment `tramvai` doesn't support Vercel edge runtime, or any other serverless environments.
Our framework setup `fastify` server, heavily integrated into the Dependency Injection system.

So, on the one hand, `tramvai` application lost the ability to be just a function like `(request, response) => HTML`.
But from the other hand, this approach has a lot benefits:
- You don't need to care, how render `React` on server or client (compared to [Remix](https://github.com/remix-run/indie-stack/blob/main/app/entry.server.tsx), for example)
- You have solid server metrics "out of the box", and can easily add custom metrics
- server lifecycle are part of application lifecycle, and by using [CommandLineRunner](https://tramvai.dev/docs/concepts/command-line-runner), you can for example run some other server for static assets or for requests mocking simultaneously with the application server (both of this cases already implemented in `tramvai` modules) 
- `tramvai` modules, thanks to DI, have full flexibility to work directly with the server instance, which allows us to implements modules where we have: cusom API endpoints, requests limits, http_proxy support, and many other specific and useful things.

**Comment by polRk** [comment]
> Our framework setup fastify server, heavily integrated into the Dependency Injection system.

Cloudflare workers, the site is rendered and displayed to users around the world in about 50ms-65ms. At the moment, no framework provides a simple way to work in cloud functions or edge functions environments.

And another question is, if I want to use koa, what should I do in this case?

**Comment by SuperOleg39** [comment]
> For example, Cloudflare workers, the site is rendered and displayed to users around the world in about 50ms-65ms

In our experience, two things significantly affect the response time of an SSR application:
- server-side requests to any API's, because of that we have some timeouts, but still it can take a hundreds of milliseconds
- server-side React rendering time for complex pages, can take from 25 to 100 ms, depends of page component complexity

Because of that, we haven't paid much attention to round-trip time.

But if we talk about cached content, no doubt RTT means a lot.
Also, we have a [static HTML export](https://coretech-frontend.pages.devplatform.tcsbank.ru/tramvai/docs/features/routing/static-html-export) feature, and these pages can be delivered to users via CDN.

**Comment by SuperOleg39** [comment]
> And another question is, if I want to use koa, what should I do in this case?

No, we decided not to made abstractions over server framework, and use only specific framework, chosen by our team.
For now, we are in the process of completing the migration from `express` to `fastify`, for performance and some others reasons.

Supporting multiple server frameworks can be too expensive for us, at least it doubles our integration tests.

**Comment by polRk** [comment]
> Supporting multiple server frameworks can be too expensive for us, at least it doubles our integration tests.

Is it possible to export an abstraction and connector functions for server frameworks ? 

```js
export handler = (req Request, res Response) {}

```

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by SuperOleg39** [comment]
Don't think so, in `server` module internal implementation we have a lot specific framework connections.

E.g. [list of internal server module tokens](https://github.com/Tinkoff/tramvai/blob/main/packages/tokens/server-private/src/index.ts), any of this can be used in other core modules.
